# Generated by Django 2.2.13 on 2020-06-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.IntegerField(verbose_name='部署')),
                ('joined_at', models.DateTimeField(verbose_name='着任時期')),
                ('quited_at', models.DateTimeField(blank=True, null=True, verbose_name='やめた時期')),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名前')),
                ('birthday', models.DateTimeField(verbose_name='誕生日')),
                ('sex', models.IntegerField(verbose_name='性別')),
                ('address_from', models.IntegerField(verbose_name='出身地')),
                ('current_address', models.IntegerField(verbose_name='現住所')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(verbose_name='着任時期')),
                ('quited_at', models.DateTimeField(blank=True, null=True, verbose_name='やめた時期')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Manager', verbose_name='担当上司')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Person', verbose_name='人')),
            ],
            options={
                'db_table': 'worker',
            },
        ),
        migrations.AddField(
            model_name='manager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Person', verbose_name='人'),
        ),
    ]
